version: "3.7"

services:

  app_proxy:
    environment:
      # The format here is: <app-id>_<docker-service-name>_1
      APP_HOST: openclaw-app_server_1
      APP_PORT: 8080

  server:
    image: 1panel/openclaw:latest
    init: true
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      - NODE_ENV=production
